CREATE DATABASE ROMAN_GEN
GO
USE ROMAN_GEN
GO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	titulo VARCHAR(70) UNIQUE NOT NULL
);
GO

CREATE TABLE TEMA (
	idTema TINYINT PRIMARY KEY IDENTITY,
	titulo VARCHAR(120) UNIQUE NOT NULL
);
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	email VARCHAR(255) UNIQUE NOT NULL,
	senha VARCHAR(40) NOT NULL,
	nome VARCHAR(70) NOT NULL
);
GO

CREATE TABLE PROJETO (
	idProjeto SMALLINT PRIMARY KEY IDENTITY,
	idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	idTema TINYINT FOREIGN KEY REFERENCES TEMA(idTema),
	titulo VARCHAR(200) NOT NULL,
	descricao VARCHAR(250)
);
GO
